import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Vaughn Chan
 */
public class GUILayout extends javax.swing.JFrame {
    
    /**
     * Method that stores all action listener overrides. 
     * Notice that all overrides call upon the objects at the bottom of this
     * file.
     * 
     * @author  Vaughn Chan
     */
    public void initActions() {
        
        // New Student Menu Item
        NewStudentMenuItem.addActionListener((ActionEvent ev) -> {
            System.out.println("Adding a new student");
        });
        
        // Add more action listeners here
    }
    
    /**
     * Creates new form GUILayout
     */
    public GUILayout() {
        initComponents();
        initActions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPane = new javax.swing.JScrollPane();
        StudentListPanel = new javax.swing.JPanel();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        EditMenu = new javax.swing.JMenu();
        NewStudentMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout StudentListPanelLayout = new javax.swing.GroupLayout(StudentListPanel);
        StudentListPanel.setLayout(StudentListPanelLayout);
        StudentListPanelLayout.setHorizontalGroup(
            StudentListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );
        StudentListPanelLayout.setVerticalGroup(
            StudentListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        ScrollPane.setViewportView(StudentListPanel);

        FileMenu.setText("File");
        MenuBar.add(FileMenu);

        EditMenu.setText("Edit");

        NewStudentMenuItem.setText("Add New Student");
        EditMenu.add(NewStudentMenuItem);

        MenuBar.add(EditMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu EditMenu;
    public javax.swing.JMenu FileMenu;
    public javax.swing.JMenuBar MenuBar;
    public javax.swing.JMenuItem NewStudentMenuItem;
    public javax.swing.JScrollPane ScrollPane;
    public javax.swing.JPanel StudentListPanel;
    // End of variables declaration//GEN-END:variables
}
